"""MCP tools: legacy generate_docs and get_module_tree.

These tools require a valid CodeWiki LLM configuration (``codewiki config set``).
They invoke the full documentation generation pipeline via the backend
DocumentationGenerator and are intended for one-shot CLI-style usage rather than
the fine-grained IDE-driven workflow.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from mcp.types import Tool

logger = logging.getLogger(__name__)


# ------------------------------------------------------------------
# Tool schemas
# ------------------------------------------------------------------

TOOLS = [
    Tool(
        name="generate_docs",
        description=(
            "[LEGACY — requires 'codewiki config set' first] "
            "Generate full documentation for a repository in one shot. "
            "For IDE-driven generation, use the fine-grained tools instead."
        ),
        inputSchema={
            "type": "object",
            "properties": {
                "repo_path": {
                    "type": "string",
                    "description": "Absolute path to the repository to document",
                },
                "output_dir": {
                    "type": "string",
                    "description": "Output directory for generated docs (default: ./repowiki)",
                    "default": "repowiki",
                },
                "doc_type": {
                    "type": "string",
                    "description": "Type of documentation to generate. Valid values defined in schema.yaml doc_types.types (default: design)",
                },
                "include_patterns": {
                    "type": "string",
                    "description": "Comma-separated file patterns to include",
                },
                "exclude_patterns": {
                    "type": "string",
                    "description": "Comma-separated patterns to exclude",
                },
            },
            "required": ["repo_path"],
        },
    ),
    Tool(
        name="get_module_tree",
        description=(
            "[LEGACY] Get the existing module clustering tree for a repository. "
            "Returns the tree structure previously saved via save_module_tree or "
            "generated by 'codewiki generate'. Use this to inspect an existing "
            "clustering before deciding whether to re-cluster. "
            "For new sessions, use save_module_tree to persist your clustering instead."
        ),
        inputSchema={
            "type": "object",
            "properties": {
                "repo_path": {
                    "type": "string",
                    "description": "Absolute path to the repository",
                },
                "output_dir": {
                    "type": "string",
                    "description": "Directory containing generated docs (default: ./repowiki)",
                    "default": "repowiki",
                },
            },
            "required": ["repo_path"],
        },
    ),
]


# ------------------------------------------------------------------
# Private helpers
# ------------------------------------------------------------------

def _load_config():
    """Load CodeWiki configuration from ~/.codewiki/config.json + keyring."""
    from codewiki.cli.config_manager import ConfigManager
    manager = ConfigManager()
    if not manager.load():
        raise RuntimeError(
            "CodeWiki not configured. Run 'codewiki config set' first."
        )
    return manager


# ------------------------------------------------------------------
# Handlers
# ------------------------------------------------------------------

async def handle_generate_docs(arguments: dict) -> str:
    """Legacy generate_docs — requires CodeWiki LLM configuration."""
    repo_path = Path(arguments["repo_path"]).expanduser().resolve()
    raw_od = Path(arguments.get("output_dir", "repowiki")).expanduser()
    output_dir = raw_od.resolve() if raw_od.is_absolute() else (repo_path / raw_od).resolve()

    if not repo_path.exists():
        return json.dumps({"error": f"Repository not found: {repo_path}"})

    manager = _load_config()
    config = manager.get_config()
    api_key = manager.get_api_key()

    from codewiki.src.be.backend import is_caw_provider
    caw_mode = bool(config) and is_caw_provider(getattr(config, "provider", ""))
    if not api_key and not caw_mode:
        return json.dumps({"error": "API key not configured. Run 'codewiki config set --api-key <key>'"})

    agent_instructions = {}
    if arguments.get("doc_type"):
        agent_instructions["doc_type"] = arguments["doc_type"]
    if arguments.get("include_patterns"):
        agent_instructions["include_patterns"] = [p.strip() for p in arguments["include_patterns"].split(",")]
    if arguments.get("exclude_patterns"):
        agent_instructions["exclude_patterns"] = [p.strip() for p in arguments["exclude_patterns"].split(",")]

    from codewiki.src.config import Config as BackendConfig, set_cli_context
    set_cli_context(True)

    backend_config = BackendConfig.from_cli(
        repo_path=str(repo_path),
        output_dir=str(output_dir),
        llm_base_url=config.base_url,
        llm_api_key=api_key,
        main_model=config.main_model,
        cluster_model=config.cluster_model,
        fallback_model=config.fallback_model,
        provider=getattr(config, "provider", "openai-compatible"),
        aws_region=getattr(config, "aws_region", "us-east-1"),
        max_tokens=config.max_tokens,
        agent_instructions=agent_instructions or None,
    )

    from codewiki.cli.utils.repo_validator import get_git_commit_hash
    from codewiki.src.be.documentation_generator import DocumentationGenerator
    doc_gen = DocumentationGenerator(backend_config, commit_id=get_git_commit_hash(repo_path) or None)
    await doc_gen.run()

    generated_files = []
    for f in output_dir.iterdir():
        if f.suffix in (".md", ".json", ".html"):
            generated_files.append(f.name)

    result = {
        "status": "success",
        "output_dir": str(output_dir),
        "files_generated": sorted(generated_files),
        "file_count": len(generated_files),
    }
    return json.dumps(result, indent=2)


async def handle_get_module_tree(arguments: dict) -> str:
    """Legacy get_module_tree."""
    repo_path = Path(arguments["repo_path"]).expanduser().resolve()
    raw_od = Path(arguments.get("output_dir", "repowiki")).expanduser()
    output_dir = raw_od.resolve() if raw_od.is_absolute() else (repo_path / raw_od).resolve()

    from codewiki.src.config import meta_resolve
    module_tree_path = Path(meta_resolve(output_dir, "module_tree.json"))
    if not module_tree_path.exists():
        return json.dumps({
            "error": f"Module tree not found at {module_tree_path}. Run 'codewiki generate' first."
        })

    module_tree = json.loads(module_tree_path.read_text(encoding="utf-8"))

    def _summarize_tree(tree, depth=0):
        lines = []
        for name, info in tree.items():
            indent = "  " * depth
            comp_count = len(info.get("components", []))
            children = info.get("children", {})
            child_count = len(children) if isinstance(children, dict) else 0
            lines.append(f"{indent}- {name} ({comp_count} components, {child_count} children)")
            if isinstance(children, dict) and children:
                lines.extend(_summarize_tree(children, depth + 1))
        return lines

    summary = "\n".join(_summarize_tree(module_tree))
    result = {
        "status": "success",
        "module_tree_path": str(module_tree_path),
        "total_modules": len(module_tree),
        "tree_summary": summary,
    }
    return json.dumps(result, indent=2)
